"""Per-protocol speed limit manager for IronPanel.

Limits are saved in AppSetting and applied with Linux tc/HTB on the default
network interface. The limiter is intentionally protocol/port based so it is
simple for admins to understand: set Mbps for a protocol, apply, and traffic
sent by the server from that protocol port is capped.
"""
from __future__ import annotations
import re, shlex
from pathlib import Path
from ..core.extensions import db
from ..core.models import AppSetting
from .provisioning import get_setting, set_setting, get_port, active_protocols, run_cmd

PROTOCOL_LABELS = {
    'openvpn': 'OpenVPN',
    'wireguard': 'WireGuard',
    'ocserv': 'Cisco / Ocserv',
    'l2tp': 'L2TP / IPsec',
    'xray': 'Xray / V2Ray',
    'pptp': 'PPTP',
    'hysteria2': 'Hysteria2',
    'telegram_proxy': 'Telegram Proxy',
    'ssh': 'SSH Tunnel',
}
PROTOCOL_ICONS = {
    'openvpn': '🔐', 'wireguard': '🧬', 'ocserv': '🛡️', 'l2tp': '🌉',
    'xray': '⚡', 'pptp': '🧷', 'hysteria2': '🚀', 'telegram_proxy': '📲', 'ssh': '⌁',
}
PROTOCOL_HELP = {
    'openvpn': 'روی پورت‌های TCP/UDP OpenVPN اعمال می‌شود.',
    'wireguard': 'روی پورت UDP وایرگارد اعمال می‌شود.',
    'ocserv': 'روی TCP/UDP سرویس Cisco AnyConnect اعمال می‌شود.',
    'l2tp': 'روی L2TP/IPsec ports اعمال می‌شود.',
    'xray': 'روی پورت اصلی Xray/V2Ray اعمال می‌شود.',
    'pptp': 'روی پورت PPTP اعمال می‌شود.',
    'hysteria2': 'روی پورت UDP Hysteria2 اعمال می‌شود.',
    'telegram_proxy': 'روی پورت مشترک Telegram Proxy اعمال می‌شود.',
    'ssh': 'روی پورت SSH Tunnel اعمال می‌شود.',
}
ALL_PROTOCOLS = list(PROTOCOL_LABELS.keys())


def _setting_key(protocol: str) -> str:
    return f'speed_limit_{protocol}_mbps'


def _sanitize_mbps(value, default=0) -> int:
    try:
        n = int(float(str(value or '').strip()))
    except Exception:
        n = int(default or 0)
    return max(0, min(n, 100000))


def protocol_ports(protocol: str):
    if protocol == 'openvpn':
        return [('udp', get_port('openvpn_udp')), ('tcp', get_port('openvpn_tcp'))]
    if protocol == 'wireguard':
        return [('udp', get_port('wireguard_udp'))]
    if protocol == 'ocserv':
        return [('tcp', get_port('ocserv_tcp')), ('udp', get_port('ocserv_udp'))]
    if protocol == 'l2tp':
        return [('udp', get_port('l2tp_udp')), ('udp', get_port('ipsec_ike')), ('udp', get_port('ipsec_nat'))]
    if protocol == 'xray':
        return [('tcp', get_port('xray_tcp'))]
    if protocol == 'pptp':
        return [('tcp', get_port('pptp_tcp'))]
    if protocol == 'hysteria2':
        return [('udp', get_port('hysteria2_udp'))]
    if protocol == 'telegram_proxy':
        return [('tcp', get_port('telegram_proxy_base'))]
    if protocol == 'ssh':
        return [('tcp', get_port('ssh_tcp'))]
    return []


def speed_limit_rows():
    active = set(active_protocols())
    rows=[]
    for protocol in ALL_PROTOCOLS:
        mbps = _sanitize_mbps(get_setting(_setting_key(protocol), '0'))
        ports = protocol_ports(protocol)
        rows.append({
            'protocol': protocol,
            'label': PROTOCOL_LABELS.get(protocol, protocol.upper()),
            'icon': PROTOCOL_ICONS.get(protocol, '◈'),
            'help': PROTOCOL_HELP.get(protocol, ''),
            'mbps': mbps,
            'enabled': mbps > 0,
            'active': protocol in active,
            'ports': ports,
            'ports_text': ', '.join([f'{p}/{proto}' for proto, p in ports]) or '-',
        })
    return rows


def save_speed_limits(form) -> list[str]:
    changed=[]
    for protocol in ALL_PROTOCOLS:
        key = _setting_key(protocol)
        value = _sanitize_mbps(form.get(key, '0'))
        old = _sanitize_mbps(get_setting(key, '0'))
        set_setting(key, str(value))
        if old != value:
            changed.append(protocol)
    db.session.commit()
    return changed


def write_speed_limit_runtime_config() -> Path:
    path = Path('/etc/ironpanel/speed_limits.conf')
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '# Generated by IronPanel. Format: protocol proto port mbps',
        '# mbps=0 means disabled and is not written here.',
    ]
    for row in speed_limit_rows():
        if row['mbps'] <= 0:
            continue
        for proto, port in row['ports']:
            if int(port or 0) > 0:
                lines.append(f"{row['protocol']} {proto} {int(port)} {int(row['mbps'])}")
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return path


def apply_speed_limits_runtime():
    write_speed_limit_runtime_config()
    script = Path('/opt/ironpanel/scripts/apply_speed_limits.sh')
    if not script.exists():
        return False, 'apply_speed_limits.sh not found. Run panel upgrade/install first.'
    p = run_cmd(['bash', str(script), '--apply'], timeout=120)
    out = (p.stdout or '') + (p.stderr or '')
    return p.returncode == 0, out[-6000:]


def speed_limit_status():
    p = run_cmd(['bash','-lc','tc -s qdisc show 2>/dev/null | head -80; echo ---; tc -s class show 2>/dev/null | head -120'], timeout=20)
    return ((p.stdout or '') + (p.stderr or '')).strip()[-8000:]
