#!/usr/bin/env bash
set -euo pipefail
CORE_ERRORS=()
APP_DIR=${APP_DIR:-/opt/ironpanel}
WIREGUARD_MTU=${IRONPANEL_WIREGUARD_MTU:-${WIREGUARD_MTU:-1280}}
ETC_DIR=${ETC_DIR:-/etc/ironpanel}
PUBLIC_HOST=${PUBLIC_HOST:-${IRONPANEL_PUBLIC_HOST:-$(hostname -I | awk '{print $1}')}}
OPENVPN_UDP=${OPENVPN_UDP:-1194}
OPENVPN_TCP=${OPENVPN_TCP:-1195}
OPENVPN_PROTO=${OPENVPN_PROTO:-${OPENVPN_TRANSPORT:-udp}}
OPENVPN_PROTO=$(echo "$OPENVPN_PROTO" | tr A-Z a-z)
if [[ "$OPENVPN_PROTO" != "tcp" ]]; then OPENVPN_PROTO=udp; fi
OPENVPN_PORT=$OPENVPN_UDP
if [[ "$OPENVPN_PROTO" == "tcp" ]]; then OPENVPN_PORT=$OPENVPN_TCP; fi
OCSERV_PORT=${OCSERV_PORT:-8445}
OCSERV_TCP=${OCSERV_TCP:-$OCSERV_PORT}
OCSERV_UDP=${OCSERV_UDP:-$OCSERV_PORT}
OCSERV_TRANSPORT=${OCSERV_TRANSPORT:-tcp_udp}
WIREGUARD_PORT=${WIREGUARD_PORT:-51820}
XRAY_PORT=${XRAY_PORT:-443}
XRAY_API_PORT=${XRAY_API_PORT:-10085}
L2TP_PORT=${L2TP_PORT:-1701}
PPTP_PORT=${PPTP_PORT:-1723}
HYSTERIA2_PORT=${HYSTERIA2_PORT:-4433}
SSH_PORT=${SSH_PORT:-422}

# v19.10.10: when this script is executed by Health Repair or manually it may
# not receive the port exports generated by upgrade.sh. Read the persisted
# settings directly from /etc/ironpanel/ironpanel.db so custom ports such as
# Ocserv/OpenConnect tcp/1195 are never reset to defaults.
read_db_runtime_settings(){
  local database_url_value="${DATABASE_URL:-}"
  local db_file="${IRONPANEL_DB:-${database_url_value#sqlite:///}}"
  [[ -n "$db_file" && "$db_file" != "$database_url_value" ]] || db_file="$ETC_DIR/ironpanel.db"
  [[ -s "$db_file" ]] || return 0
  command -v python3 >/dev/null 2>&1 || return 0
  python3 - "$db_file" <<'PYDB'
import re, shlex, sqlite3, sys
db=sys.argv[1]
def val(k, default=''):
    try:
        con=sqlite3.connect(db); cur=con.cursor(); cur.execute('select value from app_setting where key=? limit 1',(k,)); row=cur.fetchone(); con.close()
        return str(row[0]) if row and row[0] not in (None,'') else default
    except Exception:
        return default
def port(k, default):
    x=val(k, str(default)).strip()
    return x if re.fullmatch(r'\d{1,5}', x) and 0<int(x)<=65535 else str(default)
def choice(k, default, allowed):
    x=val(k, default).strip().lower()
    return x if x in allowed else default
vals={
 'OPENVPN_UDP': port('port_openvpn_udp',1194),
 'OPENVPN_TCP': port('port_openvpn_tcp',1195),
 'OPENVPN_PROTO': choice('openvpn_transport','udp',{'udp','tcp'}),
 'OCSERV_PORT': port('port_ocserv_tcp',8445),
 'OCSERV_TCP': port('port_ocserv_tcp',8445),
 'OCSERV_UDP': port('port_ocserv_udp',8445),
 'OCSERV_TRANSPORT': choice('ocserv_transport','tcp_udp',{'tcp','udp','tcp_udp'}),
 'WIREGUARD_PORT': port('port_wireguard_udp',51820),
 'XRAY_PORT': port('port_xray_tcp',443),
 'XRAY_API_PORT': port('port_xray_api',10085),
 'L2TP_PORT': port('port_l2tp_udp',1701),
 'PPTP_PORT': port('port_pptp_tcp',1723),
 'HYSTERIA2_PORT': port('port_hysteria2_udp',4433),
 'SSH_PORT': port('port_ssh_tcp',422),
 'WIREGUARD_MTU': val('wireguard_mtu','1280'),
 'IRONPANEL_WIREGUARD_MTU': val('wireguard_mtu','1280'),
}
print(' '.join(f'{k}={shlex.quote(v)}' for k,v in vals.items()))
PYDB
}
DB_RUNTIME_EXPORTS="$(read_db_runtime_settings || true)"
if [[ -n "$DB_RUNTIME_EXPORTS" ]]; then
  # shellcheck disable=SC2086
  eval "export $DB_RUNTIME_EXPORTS"
  OPENVPN_PORT=$OPENVPN_UDP
  [[ "$OPENVPN_PROTO" == "tcp" ]] && OPENVPN_PORT=$OPENVPN_TCP
fi

# A single TCP address:port cannot be shared by OpenVPN TCP and Ocserv.
# When OpenVPN TCP is selected it gets priority, otherwise generated .ovpn
# profiles can point to a port where OpenVPN is not the listening daemon.
if [[ "$OPENVPN_PROTO" == "tcp" && "$OPENVPN_TCP" == "$OCSERV_TCP" ]]; then
  if [[ "$OPENVPN_TCP" == "8445" ]]; then OCSERV_TCP=8446; else OCSERV_TCP=8445; fi
  OCSERV_PORT="$OCSERV_TCP"
  if [[ -s "$ETC_DIR/ironpanel.db" ]] && command -v python3 >/dev/null 2>&1; then
    python3 - "$ETC_DIR/ironpanel.db" "$OCSERV_TCP" <<'PYFIX' || true
import sqlite3, sys
db, port = sys.argv[1], sys.argv[2]
con=sqlite3.connect(db); cur=con.cursor()
cur.execute("CREATE TABLE IF NOT EXISTS app_setting (id INTEGER PRIMARY KEY AUTOINCREMENT, key VARCHAR(120) UNIQUE, value TEXT)")
for k,v in [('port_ocserv_tcp', port), ('port_conflict_last_fix', f'OpenVPN TCP and Ocserv TCP shared one port; Ocserv TCP moved to {port}.')]:
    cur.execute("INSERT INTO app_setting(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value", (k,v))
con.commit(); con.close()
PYFIX
  fi
fi

WAN_IF=${WAN_IF:-$(ip route get 1.1.1.1 2>/dev/null | awk '{print $5; exit}')}
mkdir -p "$ETC_DIR" /etc/openvpn/server /etc/wireguard /etc/ocserv /etc/ppp /var/log/openvpn /usr/local/etc/xray /var/log/xray
export DEBIAN_FRONTEND=noninteractive
PREREQ_SCRIPT="$APP_DIR/scripts/install_protocol_prerequisites.sh"
if [[ ! -x "$PREREQ_SCRIPT" ]]; then
  echo "IronPanel prerequisite installer is missing: $PREREQ_SCRIPT" >&2
  exit 20
fi
if ! APP_DIR="$APP_DIR" ETC_DIR="$ETC_DIR" bash "$PREREQ_SCRIPT" --install-all; then
  CORE_ERRORS+=(protocol-prerequisites)
fi
sysctl -w net.ipv4.ip_forward=1 >/dev/null || true
sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null || true
cat > /etc/sysctl.d/99-ironpanel.conf <<SYSCTL
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
SYSCTL
# NAT for every VPN subnet. Duplicate rules are avoided.
ensure_nat(){
  local subnet="$1"
  if [[ -n "${WAN_IF:-}" ]] && ! iptables -t nat -C POSTROUTING -s "$subnet" -o "$WAN_IF" -j MASQUERADE 2>/dev/null; then
    iptables -t nat -A POSTROUTING -s "$subnet" -o "$WAN_IF" -j MASQUERADE || true
  fi
}
ensure_forward(){
  local iface="$1"
  if ! iptables -C FORWARD -i "$iface" -j ACCEPT 2>/dev/null; then iptables -A FORWARD -i "$iface" -j ACCEPT || true; fi
  if ! iptables -C FORWARD -o "$iface" -j ACCEPT 2>/dev/null; then iptables -A FORWARD -o "$iface" -j ACCEPT || true; fi
}
ensure_nat 10.8.0.0/24
ensure_nat 10.44.0.0/24
ensure_nat 10.20.20.0/24
ensure_nat 10.66.66.0/24
ensure_nat 10.70.70.0/24
ensure_forward tun0
ensure_forward vpns0
ensure_forward vpns+
ensure_forward wg0
# Accept VPN listening ports on local firewall. Provider/cloud firewall must also allow them.
for rule in "${OPENVPN_UDP}/udp" "${OPENVPN_TCP}/tcp" "${OCSERV_TCP}/tcp" "${OCSERV_UDP}/udp" "${WIREGUARD_PORT}/udp" "${XRAY_PORT}/tcp" "${PPTP_PORT}/tcp" "${HYSTERIA2_PORT}/udp" "${SSH_PORT}/tcp" "500/udp" "4500/udp" "${L2TP_PORT}/udp"; do
  proto=${rule##*/}; port=${rule%%/*}
  if ! iptables -C INPUT -p "$proto" --dport "$port" -j ACCEPT 2>/dev/null; then iptables -A INPUT -p "$proto" --dport "$port" -j ACCEPT || true; fi
done
iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
# SSH core
if [[ -x "$APP_DIR/scripts/repair_ssh.sh" ]]; then
  SSH_PORT="$SSH_PORT" IRONPANEL_SSH_PORT="$SSH_PORT" bash "$APP_DIR/scripts/repair_ssh.sh" --install || CORE_ERRORS+=(ssh-repair)
fi

# OpenVPN core + complete PKI validation/repair.
# Every required artifact is validated individually; a remaining ca.crt no
# longer prevents server.crt, server.key or dh.pem from being restored.
if ! APP_DIR="$APP_DIR" ETC_DIR="$ETC_DIR" bash "$PREREQ_SCRIPT" --ensure-openvpn; then
  CORE_ERRORS+=(openvpn-pki)
fi
OPENVPN_SERVER_PROTO="udp"
if [[ "$OPENVPN_PROTO" == "tcp" ]]; then OPENVPN_SERVER_PROTO="tcp-server"; fi
OPENVPN_CRL_LINE=""
if [[ -s /etc/openvpn/server/crl.pem ]] && openssl crl -in /etc/openvpn/server/crl.pem -noout >/dev/null 2>&1; then OPENVPN_CRL_LINE="crl-verify /etc/openvpn/server/crl.pem"; fi
cat > /etc/openvpn/server/server.conf <<OVPN
port $OPENVPN_PORT
proto $OPENVPN_SERVER_PROTO
dev tun
topology subnet
server 10.8.0.0 255.255.255.0
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 8.8.8.8"
keepalive 10 120
persist-key
persist-tun
# IronPanel OpenVPN runs without privilege drop because client-connect/client-disconnect
# scripts must read/write the IronPanel SQLite database for quota enforcement.
ca /etc/openvpn/server/ca.crt
cert /etc/openvpn/server/server.crt
key /etc/openvpn/server/server.key
dh /etc/openvpn/server/dh.pem
tls-crypt /etc/openvpn/server/tls-crypt.key
auth SHA256
cipher AES-256-GCM
data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
verify-client-cert require
$OPENVPN_CRL_LINE
status /var/log/openvpn/status.log 10
status-version 2
script-security 2
client-connect /opt/ironpanel/scripts/openvpn_client_connect.sh
client-disconnect /opt/ironpanel/scripts/openvpn_client_disconnect.sh
verb 3
OVPN
for required in /etc/openvpn/server/ca.crt /etc/openvpn/server/server.crt /etc/openvpn/server/server.key /etc/openvpn/server/dh.pem /etc/openvpn/server/tls-crypt.key; do
  [[ -s "$required" ]] || CORE_ERRORS+=("openvpn-file-missing:$required")
done
# Ocserv / Cisco AnyConnect compatible core
mkdir -p /etc/ocserv/certs
if [[ -x "$APP_DIR/scripts/repair_ocserv.sh" ]]; then
  if ! OCSERV_PORT=${OCSERV_TCP:-8445} OCSERV_TCP=${OCSERV_TCP:-8445} OCSERV_UDP=${OCSERV_UDP:-8445} OCSERV_TRANSPORT=${OCSERV_TRANSPORT:-tcp_udp} IRONPANEL_PUBLIC_HOST="$PUBLIC_HOST" ETC_DIR="$ETC_DIR" bash "$APP_DIR/scripts/repair_ocserv.sh"; then
    CORE_ERRORS+=(ocserv-repair)
  fi
else
  CORE_ERRORS+=(ocserv-repair-script-missing)
fi
# L2TP/IPsec core
if [[ ! -f "$ETC_DIR/ipsec.psk" ]]; then openssl rand -base64 24 > "$ETC_DIR/ipsec.psk"; chmod 600 "$ETC_DIR/ipsec.psk"; fi
cat > /etc/ipsec.conf <<'IPSEC'
config setup
  uniqueids=no
  charondebug="ike 1, knl 1, cfg 0"
conn L2TP-PSK
  keyexchange=ikev1
  authby=secret
  type=transport
  left=%any
  leftprotoport=17/1701
  right=%any
  rightprotoport=17/%any
  auto=add
  ike=aes256-sha1-modp1024,3des-sha1-modp1024!
  esp=aes256-sha1,3des-sha1!
  rekey=no
  forceencaps=yes
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
IPSEC
cat > /etc/ipsec.secrets <<IPSECSEC
%any %any : PSK "$(cat $ETC_DIR/ipsec.psk)"
IPSECSEC
chmod 600 /etc/ipsec.secrets
cat > /etc/xl2tpd/xl2tpd.conf <<XL2TP
[global]
port = $L2TP_PORT
[lns default]
ip range = 10.20.20.10-10.20.20.250
local ip = 10.20.20.1
require chap = yes
refuse pap = yes
require authentication = yes
name = l2tpd
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes
XL2TP
cat > /etc/ppp/options.xl2tpd <<'PPP'
require-mschap-v2
ms-dns 1.1.1.1
ms-dns 8.8.8.8
asyncmap 0
auth
crtscts
lock
hide-password
modem
name l2tpd
ipparam ironpanel-l2tp
proxyarp
mtu 1280
mru 1280
noccp
lcp-echo-interval 30
lcp-echo-failure 4
PPP
touch /etc/ppp/chap-secrets; chmod 600 /etc/ppp/chap-secrets
# PPP hooks for L2TP online-session tracking. PEERNAME is provided by pppd on most xl2tpd builds.
mkdir -p /etc/ppp/ip-up.d /etc/ppp/ip-down.d
cat > /etc/ppp/ip-up.d/ironpanel-online <<'PPPHOOKUP'
#!/usr/bin/env bash
set +e
PY="/opt/ironpanel/.venv/bin/python"
[[ -x "$PY" ]] || PY="python3"
USER_NAME="${PEERNAME:-${PPP_PEER:-${IFNAME:-l2tp}}}"
REMOTE_IP="${IPREMOTE:-${5:-}}"
DEVICE_ID="${IFNAME:-${1:-ppp}}"
"$PY" /opt/ironpanel/scripts/ironpanel_session_account.py connect l2tp "$USER_NAME" "$REMOTE_IP" "$DEVICE_ID" >/dev/null 2>&1 || true
exit 0
PPPHOOKUP
cat > /etc/ppp/ip-down.d/ironpanel-online <<'PPPHOOKDOWN'
#!/usr/bin/env bash
set +e
PY="/opt/ironpanel/.venv/bin/python"
[[ -x "$PY" ]] || PY="python3"
USER_NAME="${PEERNAME:-${PPP_PEER:-${IFNAME:-l2tp}}}"
REMOTE_IP="${IPREMOTE:-${5:-}}"
DEVICE_ID="${IFNAME:-${1:-ppp}}"
"$PY" /opt/ironpanel/scripts/ironpanel_session_account.py disconnect l2tp "$USER_NAME" "$REMOTE_IP" "$DEVICE_ID" >/dev/null 2>&1 || true
exit 0
PPPHOOKDOWN
chmod +x /etc/ppp/ip-up.d/ironpanel-online /etc/ppp/ip-down.d/ironpanel-online
if [[ -x $APP_DIR/scripts/install_ppp_usage_hooks.sh ]]; then
  APP_DIR=/opt/ironpanel bash $APP_DIR/scripts/install_ppp_usage_hooks.sh || true
fi
# v19.10.10: rewrite L2TP/IPsec config through the repair script so classic
# L2TP/IPsec-PSK and Android/strongSwan IKEv2-EAP both work.
if [[ -x $APP_DIR/scripts/repair_l2tp.sh ]]; then
  IRONPANEL_PUBLIC_HOST="$PUBLIC_HOST" ETC_DIR="$ETC_DIR" L2TP_PORT="$L2TP_PORT" bash "$APP_DIR/scripts/repair_l2tp.sh" --install-core || CORE_ERRORS+=(l2tp-repair)
fi
# WireGuard core
if [[ ! -f /etc/wireguard/server_private.key ]]; then wg genkey > /etc/wireguard/server_private.key; chmod 600 /etc/wireguard/server_private.key; fi
SERVER_PRIV=$(cat /etc/wireguard/server_private.key)
SERVER_PUB=$(printf "%s" "$SERVER_PRIV" | wg pubkey)
cat > /etc/wireguard/wg0.conf.tmp <<WG
[Interface]
Address = 10.66.66.1/24
ListenPort = $WIREGUARD_PORT
PrivateKey = $SERVER_PRIV
MTU = $WIREGUARD_MTU
SaveConfig = false
PostUp = sysctl -w net.ipv4.ip_forward=1; iptables -C INPUT -p udp --dport $WIREGUARD_PORT -j ACCEPT 2>/dev/null || iptables -I INPUT -p udp --dport $WIREGUARD_PORT -j ACCEPT; iptables -C FORWARD -i %i -j ACCEPT 2>/dev/null || iptables -A FORWARD -i %i -j ACCEPT; iptables -C FORWARD -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || iptables -A FORWARD -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -C POSTROUTING -s 10.66.66.0/24 -o $WAN_IF -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s 10.66.66.0/24 -o $WAN_IF -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT 2>/dev/null || true; iptables -D FORWARD -o %i -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true; iptables -t nat -D POSTROUTING -s 10.66.66.0/24 -o $WAN_IF -j MASQUERADE 2>/dev/null || true
# BEGIN IRONPANEL PEERS
# END IRONPANEL PEERS
WG
if [[ -f /etc/wireguard/wg0.conf ]]; then
  awk 'BEGIN{keep=1} /# BEGIN IRONPANEL PEERS/{keep=0} keep{print}' /etc/wireguard/wg0.conf.tmp > /tmp/wg0.base
  awk 'f || /# BEGIN IRONPANEL PEERS/{print} /# BEGIN IRONPANEL PEERS/{f=1}' /etc/wireguard/wg0.conf > /tmp/wg0.peers || true
  cat /tmp/wg0.base /tmp/wg0.peers > /etc/wireguard/wg0.conf
else
  mv /etc/wireguard/wg0.conf.tmp /etc/wireguard/wg0.conf
fi
chmod 600 /etc/wireguard/wg0.conf
rm -f /etc/wireguard/wg0.conf.tmp /tmp/wg0.base /tmp/wg0.peers 2>/dev/null || true
echo "$SERVER_PUB" > "$ETC_DIR/wg_server_public.key"

# Xray core. The official installer is used when xray is not already installed.
# If the server has no GitHub access, install xray manually and rerun upgrade.sh.
if ! command -v xray >/dev/null 2>&1 && [[ ! -x /usr/local/bin/xray ]]; then
  curl -fsSL https://github.com/XTLS/Xray-install/raw/main/install-release.sh -o /tmp/xray-install.sh || true
  if [[ -s /tmp/xray-install.sh ]]; then bash /tmp/xray-install.sh install || true; fi
fi

ensure_xray_runtime_permissions() {
  # v16.3: use a clean IronPanel-managed unit instead of the upstream unit/drop-ins.
  # The upstream installer may leave User=nobody and our old v16.1 drop-in had
  # DynamicUser= with an empty value, which systemd rejects as "Failed to parse
  # boolean value". When that drop-in is ignored, Xray keeps running as nobody
  # and cannot open /var/log/xray/access.log.
  install -d -m 755 -o root -g root /usr/local/etc/xray 2>/dev/null || mkdir -p /usr/local/etc/xray
  install -d -m 755 -o root -g root /var/log/xray 2>/dev/null || mkdir -p /var/log/xray
  touch /var/log/xray/access.log /var/log/xray/error.log 2>/dev/null || true
  chown root:root /var/log/xray /var/log/xray/access.log /var/log/xray/error.log 2>/dev/null || true
  chmod 755 /var/log/xray 2>/dev/null || true
  chmod 644 /var/log/xray/access.log /var/log/xray/error.log 2>/dev/null || true
  if [[ -f /usr/local/etc/xray/config.json ]]; then
    chown root:root /usr/local/etc/xray/config.json 2>/dev/null || true
    chmod 644 /usr/local/etc/xray/config.json 2>/dev/null || true
  fi
  if [[ -x /usr/local/bin/xray || -x /usr/bin/xray || -n "$(command -v xray 2>/dev/null || true)" ]]; then
    XRAY_BIN="$(command -v xray 2>/dev/null || true)"
    [[ -n "$XRAY_BIN" ]] || XRAY_BIN=/usr/local/bin/xray
    # Remove broken/old drop-ins, including:
    # - 10-donot_touch_single_conf.conf from the official installer
    # - 20-ironpanel-runtime.conf from v16.1/v16.2 with DynamicUser=
    if [[ -d /etc/systemd/system/xray.service.d ]]; then
      BACKUP_DIR="/etc/systemd/system/xray.service.d.ironpanel-backup-$(date +%Y%m%d%H%M%S)"
      mkdir -p "$BACKUP_DIR" 2>/dev/null || true
      cp -a /etc/systemd/system/xray.service.d/. "$BACKUP_DIR"/ 2>/dev/null || true
      rm -rf /etc/systemd/system/xray.service.d
    fi
    cat > /etc/systemd/system/xray.service <<EOF_SERVICE
[Unit]
Description=Xray Service - IronPanel Managed
Documentation=https://github.com/XTLS/Xray-core
After=network.target nss-lookup.target
Wants=network.target

[Service]
Type=simple
User=root
Group=root
ExecStartPre=/bin/sh -c 'mkdir -p /var/log/xray /usr/local/etc/xray; touch /var/log/xray/access.log /var/log/xray/error.log; chmod 755 /var/log/xray; chmod 644 /var/log/xray/access.log /var/log/xray/error.log'
ExecStart=$XRAY_BIN run -config /usr/local/etc/xray/config.json
Restart=on-failure
RestartSec=5s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF_SERVICE
  fi
}

ensure_xray_runtime_permissions
if [[ ! -f /usr/local/etc/xray/config.json ]]; then
  cat > /usr/local/etc/xray/config.json <<XRAYJSON
{
  "log": {"loglevel": "warning", "access": "/var/log/xray/access.log", "error": "/var/log/xray/error.log"},
  "inbounds": [{"tag":"ironpanel-xray","listen":"0.0.0.0","port": $XRAY_PORT,"protocol":"vless","settings":{"clients":[],"decryption":"none"},"streamSettings":{"network":"tcp","security":"none"}}],
  "outbounds": [{"tag":"direct","protocol":"freedom"}]
}
XRAYJSON
fi
# Open firewall if ufw is active. Cloud firewall must still be opened by provider.
if command -v ufw >/dev/null 2>&1 && ufw status | grep -qi active; then
  ufw allow "${OPENVPN_UDP}/udp" || true
  ufw allow "${OPENVPN_TCP}/tcp" || true
  ufw allow "${OCSERV_TCP}/tcp" || true
  ufw allow "${OCSERV_UDP}/udp" || true
  ufw allow "${WIREGUARD_PORT}/udp" || true
  ufw allow "${XRAY_PORT}/tcp" || true
  ufw allow 500/udp || true
  ufw allow 4500/udp || true
  ufw allow "${L2TP_PORT}/udp" || true
fi
ensure_xray_runtime_permissions
systemctl daemon-reload
systemctl enable openvpn-server@server xray ocserv strongswan-starter xl2tpd wg-quick@wg0 >/dev/null 2>&1 || true
systemctl restart openvpn-server@server || CORE_ERRORS+=(openvpn-restart)
ensure_xray_runtime_permissions
systemctl restart xray || CORE_ERRORS+=(xray-restart)
systemctl restart ocserv || CORE_ERRORS+=(ocserv-restart)
systemctl restart strongswan-starter || systemctl restart strongswan || ipsec restart || CORE_ERRORS+=(ipsec-restart)
systemctl restart xl2tpd || CORE_ERRORS+=(xl2tpd-restart)
systemctl restart wg-quick@wg0 || CORE_ERRORS+=(wireguard-restart)
# v18 legacy/new cores
if [[ -x "$APP_DIR/scripts/repair_pptp.sh" ]]; then bash "$APP_DIR/scripts/repair_pptp.sh" || CORE_ERRORS+=(pptp-repair); fi
if [[ -x "$APP_DIR/scripts/repair_hysteria2.sh" ]]; then HYSTERIA2_PORT=${HYSTERIA2_PORT:-4433}
SSH_PORT=${SSH_PORT:-422} HYSTERIA2_UP="${HYSTERIA2_UP:-100 mbps}" HYSTERIA2_DOWN="${HYSTERIA2_DOWN:-300 mbps}" bash "$APP_DIR/scripts/repair_hysteria2.sh" || CORE_ERRORS+=(hysteria2-repair); fi
if command -v ocserv >/dev/null 2>&1; then
  systemctl is-active --quiet ocserv || CORE_ERRORS+=(ocserv-inactive)
  ss -lnt 2>/dev/null | awk '{print $4}' | grep -Eq "(^|:)${OCSERV_TCP}$" || CORE_ERRORS+=(ocserv-port-not-listening)
else
  CORE_ERRORS+=(ocserv-binary-missing)
fi
if [[ -x "$APP_DIR/scripts/protocol_health_check.sh" ]]; then
  APP_DIR="$APP_DIR" ETC_DIR="$ETC_DIR" bash "$APP_DIR/scripts/protocol_health_check.sh" > /var/log/ironpanel-protocol-health.log 2>&1 || true
fi

cat <<INFO
Ironpanel VPN cores installed/updated:
- OpenVPN: $OPENVPN_PROTO/$OPENVPN_PORT
- Ocserv/Cisco AnyConnect: transport/$OCSERV_TRANSPORT tcp/$OCSERV_TCP udp/$OCSERV_UDP
- WireGuard: udp/$WIREGUARD_PORT
- L2TP/IPsec: udp/500 udp/4500 udp/$L2TP_PORT
- PPTP: tcp/$PPTP_PORT
- Hysteria2: udp/$HYSTERIA2_PORT
INFO
if (( ${#CORE_ERRORS[@]} > 0 )); then
  printf 'IronPanel core validation errors: %s\n' "${CORE_ERRORS[*]}" >&2
  exit 30
fi
